# Generated by Django 4.0.3 on 2022-03-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField()),
                ('update_power', models.DateTimeField()),
                ('actual_power', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatusDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status_device', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['status_device'],
            },
        ),
        migrations.CreateModel(
            name='TypeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('type_device', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['type_device'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('actual_power', models.DecimalField(decimal_places=10, max_digits=19)),
                ('timestamp', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
                ('type_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typedevice')),
            ],
            options={
                'ordering': ['device'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='status_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statusdevice'),
        ),
        migrations.AddField(
            model_name='device',
            name='type_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typedevice'),
        ),
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('actual_power', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
            options={
                'ordering': ['device'],
            },
        ),
    ]
