# Generated by Django 4.0.3 on 2022-03-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binnacle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='binnacle',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='binnacle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='statusdevice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statusdevice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='statusdevice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='typedevice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='typedevice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='typedevice',
            name='updated_at',
        ),
    ]
